version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: always
    environment:
      PORT: 8080  
      DB_DATABASE: ${DB_DATABASE}  
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD}  
      DB_PORT: ${DB_PORT}  

  nginx:
    build:
      context: ./ngnix  
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always

  psql:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}  
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "${DB_PORT}:5432"  
    volumes:
      - psql_volume:/var/lib/postgresql/data  

volumes:
  psql_volume:
