FROM mongo:latest

COPY init.js /docker-entrypoint-initdb.d/


ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
ENV MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
ENV DOC_USERNAME=${DOC_USERNAME}
ENV DOC_PASSWORD=${DOC_PASSWORD}

EXPOSE 27017
