version: '3.8' 

services:
  mongodb:
    image: mongo:latest  
    container_name: mongodb_container  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}  
    ports:
      - "${MONGO_PORT}:27017"  
    volumes:
      - mongodb_data:/data/db  
volumes:
  mongodb_data:  
